version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest pytest-html
      - run:
          name: Run tests and generate HTML report
          command: |
            . venv/bin/activate
            pytest --html=report.html --self-contained-html
      - store_artifacts:
          path: report.html
          destination: pytest_html_report
      - store_artifacts:
          path: test_log.log
          destination: test_logs

workflows:
  version: 2
  test:
    jobs:
      - test
