version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9  # Використання образу з Python 3.9
    working_directory: ~/repo

jobs:
    test:
      executor: python-executor
      steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
              . venv/bin/activate
              python -m venv venv
              pip install -r requirements.txt
              pip install pytest pytest-html python-dotenv
              pip install "python-dotenv[cli]"
        - run:
            name: Run tests and generate report
            command: |
              . venv/bin/activate
              pytest Tests --html=report.html --self-contained-html
        - store_artifacts:
            path: ClickUpPython/report.ntml
            destination: pytest_html_report

workflows:
  version: 2
  test:
    jobs:
      - test
